name: YouTube Monitor

on:
  schedule:
    # roda às 10h da manhã a cada 2 dias
    - cron: "0 10 */2 * *"
  workflow_dispatch: # permite rodar manualmente também

jobs:
  run-rpa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install --force-reinstall --no-cache-dir numpy==1.26.2
          pip install --force-reinstall --no-cache-dir pandas==2.1.1 openpyxl==3.1.2 google-api-python-client==2.88.0



      - name: Rodar script RPA
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: |
          python main.py
